# Generated by Django 5.1.1 on 2024-09-13 04:37

import app.books.models
import autoslug.fields
import django.db.models.deletion
import django_tiptap.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "cover_photo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Library",
                "verbose_name_plural": "Book Libraries",
                "db_table": "books",
            },
        ),
        migrations.CreateModel(
            name="BooksChapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("chapter_number", models.IntegerField()),
                ("images", models.CharField(blank=True, max_length=255, null=True)),
                ("content", django_tiptap.fields.TipTapTextField()),
                ("is_draft", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="books.books",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter per book",
                "verbose_name_plural": "Chapters per book",
                "db_table": "books_chapter",
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "constraints": [
                    models.UniqueConstraint(
                        app.books.models.Lowercase("name"), name="unique_lowercase_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="books",
            name="category",
            field=models.ManyToManyField(blank=True, to="books.categories"),
        ),
    ]
