# Generated by Django 5.1.1 on 2024-09-13 13:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookschapter",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
