# Generated by Django 5.1.1 on 2024-09-13 23:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_bookschapter_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookschapter",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
