# Generated by Django 5.1.1 on 2024-09-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_bookschapter_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookschapter",
            name="content",
            field=models.TextField(),
        ),
    ]
