# Generated by Django 5.1.1 on 2024-09-14 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_bookschapter_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersStartedChapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_PROGRESS", "IN_PROGRESS"), ("DONE", "DONE")],
                        max_length=100,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="started_chapters",
                        to="books.bookschapter",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        help_text="The user associated with this record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books_chapter_reader",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reader",
                    ),
                ),
            ],
            options={
                "verbose_name": "User's Started Chapter",
                "db_table": "users_started_chapter",
                "managed": True,
            },
        ),
    ]
