# Generated by Django 5.1.1 on 2024-09-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_usersstartedchapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookschapter",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
