# Generated by Django 5.1.1 on 2024-09-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_alter_books_co_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="books",
            old_name="co_author",
            new_name="co_authors",
        ),
    ]
