# Generated by Django 5.1.1 on 2024-09-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_plagiarismcheckerlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="plagiarismcheckerlogs",
            name="log_id",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
