# Generated by Django 5.1.1 on 2024-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_plagiarismcheckerlogs_log_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="plagiarismcheckerlogs",
            name="words_count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
