# Generated by Django 5.1.1 on 2024-09-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
