# Generated by Django 5.1.1 on 2024-09-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_gender_alter_user_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
