# Generated by Django 5.1.1 on 2024-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
