# Generated by Django 5.1.1 on 2024-09-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_newsfeed", "0002_alter_socialpost_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="media",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
